db:
    host: 127.0.0.1
    port: 3308
    user: root
    passwd: root
    db: safeskiing

mqtt:
    host: 192.168.1.150
    client_id: Subscriber_safeskiing
    station-topic: /+/UUIDs
    nfc-topic: /NFC/+
    totalpeople-topic: /+/totalPeople
    qos: 2