db:
    host: localhost
    port: 3306
    user: root
    passwd: root
    db: safeskiing

mqtt:
    host: localhost
    client_id: Subscriber_safeskiing
    station-topic: /+/UUIDs
    nfc-topic: /NFC/+
    totalpeople-topic: /+/totalPeople
    qos: 2